### ISSUE TITLE
Dice picture not found

### ISSUE THREAD

**Issue by imdodrill** [I461-Bridge/Level#21] opened 2017-06-05 21:21 UTC
From the start page, select any class or level and then click 'Go'.  I've used fighter and level 3, but I have seen it on all of the classes and all of the levels that I checked.

The page loads correctly, but there is a 404 error for an image beneath the description for rolling the dice.  The image is d10.png or d8.png, depending on the page you visit.  Below are the references to the images that are returning 404 errors:
http://students.washington.edu/images/d8.png
http://students.washington.edu/images/d10.png

**Comment by isabelgiang** [comment] 2017-06-07 23:08
Thank you for pointing this out! Your suggestions were helpful in getting us closer to the cause of the problem. As this concerns the dice images not being visible, I've marked this as a duplicate of #11 .

**Comment by isabelgiang** [comment] 2017-06-07 23:18
Resolved with recent merge of #25.

**Closed as completed by isabelgiang** 2017-06-07 23:18 UTC
Labels: duplicate
