### ISSUE TITLE
Dice image not loading

### ISSUE THREAD

**Issue by FXStrato** [I461-Bridge/Level#18] opened 2017-06-05 19:05 UTC
After choosing a class, and then selecting level, it brings me to this screen, and I believe an image of a dice is supposed to show up. However, it appears to have broken. 

![image](https://cloud.githubusercontent.com/assets/5132248/26798884/35173320-49e7-11e7-9aee-f71cb0ba6eba.png)

**Comment by isabelgiang** [comment] 2017-06-07 23:09
Thank you for your feedback! As this is about the dice images not being visible, I've marked this as a duplicate of #11.

**Comment by isabelgiang** [comment] 2017-06-07 23:18
Resolved with recent merge of #25.

**Closed as completed by isabelgiang** 2017-06-07 23:18 UTC
Labels: duplicate
